name: Deploy Docker a Elastic Beanstalk

on:
  push:
    branches: [ "main" ]

# Permisos necesarios para subir paquetes a GitHub Container Registry
permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Bajar el código
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configurar Java 17 (Cambio 25 por 17 para evitar el error de Lombok)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Compilar (saltamos tests para ir más rápido)
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Login en GitHub Container Registry
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. Calcular nombre de imagen en minúsculas
      - name: Lowercase Image Name
        run: |
          echo "IMAGE_NAME=$(echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # 6. Construir y Subir Imagen Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.run_number }}

      # 7. Generar archivo docker-compose.yml para AWS
      - name: Generate docker-compose.yml
        run: |
          echo "services:
            app:
              image: ${{ env.IMAGE_NAME }}:${{ github.run_number }}
              ports:
                - '80:8080'
              environment:
                - SPRING_DATASOURCE_URL
                - SPRING_DATASOURCE_USERNAME
                - SPRING_DATASOURCE_PASSWORD
              restart: always" > docker-compose.yml

      # 8. Desplegar en AWS Elastic Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          application_name: HogwartsAPI
          environment_name: HogwartsAPI-env
          version_label: ${{ github.run_number }}
          region: us-east-1
          deployment_package: docker-compose.yml